### ISSUE TITLE
Slow fps on linux

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/bsnes2014#10]
I'm experiencing some slowdow, ~43 fps in balanced and 56 fps in performance. This, in a core i7 4700HQ, xubuntu 14.04.

Some time ago, they had high cpu usage, much more than mercury.

perf of balanced core:

![bsnes_balanced_perf_top](https://cloud.githubusercontent.com/assets/5431285/8021165/13e5085a-0c6b-11e5-8fc8-88d0ec40a6a0.png)

perf of performance core:

![bsnes_performance_perf_top](https://cloud.githubusercontent.com/assets/5431285/8021182/7afa36f0-0c6b-11e5-99ac-708200e8defe.png)

**Comment by andres-asm** [comment]
the cores haven't really changed though, this might be more of a setup issue than a bug

**Comment by sergiobenrocha2** [comment]
setup? Well, I'm with the default config, I erased the config folder.

I tried with the balanced core from builtbot, it has the same perf. But with Zelda Link to the Past, it has a different perf, running with 48 fps:

![bsnes_balanced_perf_top_core_uploader_zelda_link_to_the_past](https://cloud.githubusercontent.com/assets/5431285/8021448/97492a68-0c76-11e5-8afb-bee281990152.png)

**Comment by sergiobenrocha2** [comment]
Ok, now it's 60 fps, but with high CPU usage, nearly 96°C, 141% cpu

**Comment by sergiobenrocha2** [comment]
ugh, it's unstable, sometimes it get 60 fps with high cpu usage, and in the same game it drops the fps

**Comment by sergiobenrocha2** [comment]
Seems @33c43dc fix it
