### ISSUE TITLE
Any bsnes core after 2015-12-17 crashes upon launching a game.

### ISSUE THREAD

**Issue by alabrand** [libretro/bsnes2014#13]
Any bsnes core before 2015-12-17: Success! The game successfully launches.

Any bsnes core after 2015-12-17: Fail! The game does not launch at all.

**Comment by saftle** [comment]
I'm having the same issue, but only with certain games, and only when launched via commandline "E:\Emulation\Emulators\RetroArch\retroarch.exe" -f -L E:\Emulation\Emulators\RetroArch\cores\bsnes_balanced_libretro.dll "E:\Emulation\Roms\SNES\Seiken Densetsu 3.zip"

**Comment by Awakened0** [comment]
The command line launching issue with certain games is fixed now.

**Comment by ghost** [comment]
I can't reproduce this at all, I'm using the Bsnes Accuracy profile core built recently and every game I own loads perfectly through Retroarch, command line and through the RAEM frontend.

Anyone else that still having problem with this?

**Comment by saftle** [comment]
A newer build fixed my issue with certain games. I haven't seen the problem since.
