### ISSUE TITLE
Compiler isn't able to find object file

### ISSUE THREAD

**Issue by luigoalma** [libretro/bsnes2014#2]
Hello,

I tried compile this by running make -j2 platform=x profile=balanced target=libretro
Started fine but i got this error:
cc   build.o obj/libco.o obj/processor-arm.o obj/processor-gsu.o obj/processor-hg51b.o obj/processor-lr35902.o obj/processor-r65816.o obj/processor-spc700.o obj/processor-upd96050.o obj/sfc-interface.o obj/sfc-system.o obj/sfc-controller.o obj/sfc-cartridge.o obj/sfc-cheat.o obj/sfc-memory.o obj/sfc-cpu.o obj/sfc-smp.o obj/sfc-dsp.o obj/sfc-ppu.o obj/sfc-satellaviewbase.o obj/sfc-icd2.o obj/sfc-bsx.o obj/sfc-nss.o obj/sfc-event.o obj/sfc-sa1.o obj/sfc-superfx.o obj/sfc-armdsp.o obj/sfc-hitachidsp.o obj/sfc-necdsp.o obj/sfc-epsonrtc.o obj/sfc-sharprtc.o obj/sfc-spc7110.o obj/sfc-sdd1.o obj/sfc-obc1.o obj/sfc-hsu1.o obj/sfc-msu1.o obj/sfc-satellaviewcart.o obj/sfc-sufamiturbo.o obj/gb-interface.o obj/gb-system.o obj/gb-scheduler.o obj/gb-memory.o obj/gb-cartridge.o obj/gb-cpu.o obj/gb-ppu.o obj/gb-apu.o obj/gb-cheat.o obj/gb-video.o obj/libretro.o   -o build
cc: error: build.o: No such file or directory
<builtin>: recipe for target 'build' failed
make: **\* [build] Error 1

**Comment by Sir-Walrus** [comment]
The bsnes makefiles are a bit buggy and unfriendly. Part of this is user error (platform=x should be platform=unix), but I pushed in some fixes to make things more friendly.
