### ISSUE TITLE
No sound after loading savestate

### ISSUE THREAD

**Issue by Kierek** [libretro/bsnes2014#29]
This core has been recently updated in Arch Linux(jump from 464 to newest 499 commits version). Now, after loading savestate sound disappears, I have to restart Retroarch to get it back. It's not arch's package specific, since when compiled directly from git the same happens.

**Comment by orbea** [comment]
I can't reproduce this in Slackware current.

What game and accuracy profile can you reproduce this with? What version of RetroArch?

Can you git bisect it to find when the issue started?

**Comment by Kierek** [comment]
It seems that now it's only happening with package from Arch repo, when compiled directly from git it's working perfectly fine and I also can't reproduce it, strange. I will report it there.
