### ISSUE TITLE
Update Bsnes v107

### ISSUE THREAD

**Issue by ToniBC** [libretro/bsnes2014#60]
I recently updated this emulator with many improvements in its operation, engine, speed, etc ... It allows loading the MSU1 like Snes9x, it does not require a manifest, it does not have profiles, come on, it was updated in many aspects.

It would be nice if a port of this version was updated or created.

Thank you.

**Comment by andres-asm** [comment]
Bsnes core is not the same as byuu's new bsnes.
It would be a new core.

**Comment by ToniBC** [comment]
Ok, then it will take a long time to adapt. I put it here because programmers always comment that you have to notify things to have a list of tasks to look at.

Thank you, we just need to wait and see if anyone is encouraged.

**Comment by hizzlekizzle** [comment]
I'm pretty sure it's not going to come from us. We gave the higan v106 libretroization upstream with the understanding that they would keep it going. It's not really possible for us to keep up with the sorts of changes that have happened since then.
